import "./globals.css";
import Navbar from "./(global-layout)/Navbar";
import Footer from "./(global-layout)/Footer";


// Fonts

import { duel, instrumentSans } from "@/styles/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${duel.variable} ${instrumentSans.variable} font-sans`}>
        {/* <Navbar /> */}
        <main>{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
